### ISSUE TITLE
Full sample project?

### ISSUE THREAD

**Issue by metasection** [mpociot/teamwork#1]
Hi, is there a full sample project available?  Thanks.

**Comment by mpociot** [comment]
Hi,

no there isn't yet. Do you miss something from the documentation?

**Comment by metasection** [comment]
We are starting a new project soon.  Teamwork will be very useful.  We need admin UI functionality.  

New to Laravel (moving from other frameworks).  
Was planning to start project using this boilerplate.

https://github.com/rappasoft/laravel-5-boilerplate/blob/master/readme.md
