### ISSUE TITLE
Missing argument 1 for Mpociot\Teamwork\Teamwork::__construct(), called in C:\wamp\www\LOLPLATFORM\app\Http\Controllers\TeamsController.php on line 30 and defined

### ISSUE THREAD

**Issue by minedun6** [mpociot/teamwork#10]
i did exactly as the documentation said and i got this error when i tried to execute it -_-

Here's what i wrote

public function create(Request $request)
    {
        $team = new Team();
        $team->owner_id = User::find($request->get('leader'));
        $team->name = $request->get('name');
        $team->save();

```
}
```

**Comment by mpociot** [comment]
Hi,

Did you add `Mpociot\Teamwork\TeamworkServiceProvider::class`
To your config/app.php ?

**Comment by minedun6** [comment]
yes i did, I followed all steps

**Comment by mpociot** [comment]
Can you tell me, what line 30 in the TeamsController is?
Which version of laravel are you using?

**Comment by minedun6** [comment]
here's the code : 
public function create(Request $request)
    {
        $team = new Team();
        $team->owner_id = User::where('username', '=', 'sebastian')->first()->getKey();
        $team->name = 'My awesome team';
        $team->save();
    }

and I'm using L5

**Comment by mpociot** [comment]
I need the code on line 30, not the whole block

**Comment by minedun6** [comment]
$team = new Team();

**Comment by mpociot** [comment]
Hm, OK. Can you give me the full error output?
The issue title got truncated. 

And how does your Team model look like?

**Comment by minedun6** [comment]
For the team model it's just  
class Team extends TeamWork{}

As for the full error it's 

ErrorException in Teamwork.php line 24:
Missing argument 1 for Mpociot\Teamwork\Teamwork::__construct(), called in C:\wamp\www\IAmLegend\app\Http\Controllers\TeamsController.php on line 30 and defined

**Comment by mpociot** [comment]
Ah, that's the problem. The team model should extend TeamworkTeam.

Like this:

`class Team extends TeamworkTeam
{
}`

**Comment by minedun6** [comment]
Yeaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaah My bad !!
I was really stupid to forget that !!
