### ISSUE TITLE
Support for Laravel 5.8

### ISSUE THREAD

**Issue by ahoiroman** [mpociot/teamwork#107]
Does this package support Laravel 5.8 ?

**Comment by tanthammar** [comment]
+1 for this request

**Comment by oliuz** [comment]
I made fork of the package and I did full for Laravel 5.8 in addition to adding other functions and edit migrations and other things.

**Comment by tanthammar** [comment]
> I made fork of the package and I did full for Laravel 5.8 in addition to adding other functions and edit migrations and other things.

@oliuz can you share your package?

**Comment by shealan** [comment]
Still no support for Laravel 5.8? I'd love to use this for a forthcoming project but worried it has stalled. I can't find anything else as well designed and thought out.

**Comment by oliuz** [comment]
> Still no support for Laravel 5.8? I'd love to use this for a forthcoming project but worried it has stalled. I can't find anything else as well designed and thought out.

Hi, @shealan 

I already have this same package with support for Laravel 5.8

[Package Link](https://github.com/oliuz/teamwork)

**Comment by shealan** [comment]
@oliuz thanks I am going to give that a try today :)

**Comment by oliverpool** [comment]
@shealan beware, the whole git history has been removed: https://github.com/oliuz/teamwork/issues/1

**Comment by oliuz** [comment]
@oliverpool 
I ask, have I changed anything in the name of the creator of the package?
I already explained about that and you do not just understand.

**Comment by judgej** [comment]
@oliverpool author makes it clear his repo [is NOT a github fork](https://github.com/oliuz/teamwork/issues/1#issuecomment-475698456) so there is no history, though he does say it is fork in this thread. It's just a snapshot of the source code *as some time* and uploaded as a new repository.

Personally, I would be happier doing a tracked fork of this project, and merging in those changes, so the full history is available, PRs can be raised if relevant, and everyone has a better view of the relationship between the forks.

There are already [over 100 forks](https://github.com/mpociot/teamwork/network) and splitting off without any links is not going to give any confidence this will be further maintained.

**Comment by okaufmann** [comment]
As of this package is maintained again, maybe we can reunite these two again? What do you think @oliuz ?

**Comment by okaufmann** [comment]
As of Laravel 5.8 is no more officially supported, I think we should not too...
https://laravel.com/docs/5.8/releases#support-policy
