### ISSUE TITLE
Is there a way in the package to specify the limit of members in a team or to limit an X user as leader ?

### ISSUE THREAD

**Issue by minedun6** [mpociot/teamwork#11]
Is there a way in the package to specify the limit of members in a team or to limit an X user as leader ?
let's say I have a user x and i want this user to be leader only in y team, even if he can be in other teams, he can be leader only in one ?

**Comment by mpociot** [comment]
No, you will need to implement these features on your own.
I think this depends a lot on the use case and doesn't fit in the general package. 

So you would for example need to use the `isTeamOwner()`  method in the user, before allowing him to he the owner of another team.

**Comment by minedun6** [comment]
you mean i need to create custom validators, am I right ?

**Comment by mpociot** [comment]
Yes, exactly
