### ISSUE TITLE
Is this package dead?

### ISSUE THREAD

**Issue by herroworrd** [mpociot/teamwork#113]
Would be interested to hear from owner if this package is dead and what future plans he may have. I think we're getting beyond a reasonable timeframe waiting on this version roll.

**Comment by LorenzoSapora** [comment]
Yes.

**Comment by okaufmann** [comment]
No! I'll will maintain the package for marcel from know on.

**Comment by mpociot** [comment]
Thanks again for stepping up @okaufmann 👏 
Very much appreciated

**Comment by okaufmann** [comment]
Sure!
