### ISSUE TITLE
can not install for laravel 6.*

### ISSUE THREAD

**Issue by cypherinc** [mpociot/teamwork#117]
I am not able to install the package for laravel 6.0, however, the doc says it's for the laravel 7 and above only but I saw a commit which says added support for laravel 6.0

Problem 1
```
    - Can only install one of: laravel/framework[v6.18.20, 7.x-dev].
    - Can only install one of: laravel/framework[7.x-dev, v6.18.20].
    - Can only install one of: laravel/framework[7.x-dev, v6.18.20].
    - mpociot/teamwork 6.0.0 requires laravel/framework ^7.0 -> satisfiable by laravel/framework[7.x-dev].
    - Installation request for mpociot/teamwork ^6.0 -> satisfiable by mpociot/teamwork[6.0.0].
    - Installation request for laravel/framework == 6.18.20.0 -> satisfiable by laravel/framework[v6.18.20].

```

**Comment by oliuz** [comment]
Hi @cypherinc 

What version do you have of Laravel 6? since you can install from the version v6.18.20 or above

**Comment by jadamec** [comment]
Same problem here, I'm using version 6.18.22 of Laravel and in composer.json I've  `"laravel/framework": "^6.0",`. Thanks.

**Comment by cypherinc** [comment]
> Same problem here, I'm using version 6.18.22 of Laravel and in composer.json I've `"laravel/framework": "^6.0",`. Thanks.

sorry for the late reply, but I had to downgrade the package version to 5.3.0 in order to make it work.

**Comment by cypherinc** [comment]
> Hi @cypherinc
> 
> What version do you have of Laravel 6? since you can install from the version v6.18.20 or above

hi, the problem was with the exact same version, `laravel 6.18.20`

**Comment by okaufmann** [comment]
Which PHP version do you use?

**Comment by cypherinc** [comment]
> Which PHP version do you use?

7.2

**Comment by okaufmann** [comment]
try install it explicitly with `composer require mpociot/teamwork:6.0.1`  (this is the version with the fix for laravel 6.*) maybe the wildcard ^6.0 causing the problem. Just guessing as I can't reproduce your error :/

**Comment by okaufmann** [comment]
Just found the problem: packagist did not get updated version 6.0.1 properly (https://packagist.org/packages/mpociot/teamwork). I release an empty version 6.0.2 which should now work for you.

I just created an empty composer project using `laravel/framework:6.18.20` and was able to install this package through 
`composer require mpociot/teamwork`
