### ISSUE TITLE
Is it possible to override the default behaviour of the inviteteam ?

### ISSUE THREAD

**Issue by minedun6** [mpociot/teamwork#12]
I would like not to send an email but to make the invite process through the site by doing something like what Facebook does with their invitation system ? Is is possible ?

**Comment by mpociot** [comment]
I don't know what you mean with "Facebook invitation system", but you're totally free to notify the users however you like.

``` php
Teamwork::inviteToTeam( $email, $team, function( $invite )
{
    // Send slack message..
    // Send facebook message 
   // Sent internal message to user $invite->user
});
```

There's no restriction to send an email.

**Comment by minedun6** [comment]
What I meant is that I was talking about the notifications system/the add friend system, i don't want to email them but i want the accept/refuse invitation process to go inside the site.

**Comment by mpociot** [comment]
Well, feel free to implement it this way.

But this has nothing to do with this package.

If you want to list all (open) invitations from your user, use the  `invites` relation on your `User` model.
