### ISSUE TITLE
Add support php 8

### ISSUE THREAD

**Issue by siarheipashkevich** [mpociot/teamwork#129]
Could you please add support of php 8?

**Comment by ahoiroman** [comment]
Any chance to help here, @mpociot ? The pull request does exist and I'd be really happy if I could help you out here as I want to use this package in my PHP8-only Laravel-project.

**Comment by okaufmann** [comment]
Hi @ahoiroman. Marcel is no longer maintaining this Repo. I did merge a new PR fixing tests and adding PHP 8 support (https://github.com/mpociot/teamwork/pull/131). A new Version containing this PR was also released: https://github.com/mpociot/teamwork/releases/tag/6.1.2.

**Comment by siarheipashkevich** [comment]
@okaufmann thanks a lot.
