### ISSUE TITLE
it has a way to bind the team to multiple fields on the same model

### ISSUE THREAD

**Issue by ggafiled** [mpociot/teamwork#134]
Sorry, it has a way to bind the team to multiple fields on the same model like this? I want to get a team and member list by each field that references the team model. 
![image](https://user-images.githubusercontent.com/35791150/114256886-9d913880-99e6-11eb-90dd-a9bdc0c0a6d5.png)

**Comment by okaufmann** [comment]
I am not sure if I understand your requirement correctly. 
But if you want to have further fields on the team model you can just ad them to the Database and extend the Team model.

**Comment by ggafiled** [comment]
on Constarution Model i need to bind surveyDesignTeam, surveyDesingDateBy, ifccTeam, wallBoxTeam to reference to id on Team model
in document to see only one field reference to id on Team but my case it's mutiple field to reference team model.
@okaufmann

**Comment by okaufmann** [comment]
unfortunately not. This is a limitation of https://github.com/mpociot/teamwork/blob/master/src/Traits/UserHasTeams.php

**Comment by okaufmann** [comment]
I'll close this issue for now.
