### ISSUE TITLE
[QUESTION] Possible for Other Models

### ISSUE THREAD

**Issue by ghost** [mpociot/teamwork#135]
Marcel,

Is it possible to create teams based on a different model?

I'd like to have my companies model be the owner of the team, then be able to add users from that company to different teams.

Would I need to rewrite large sections of this, or would that scenario drop right in via configs?

Thanks

**Comment by okaufmann** [comment]
You could try to add the trait to your model like https://github.com/mpociot/teamwork#user

**Comment by ghost** [comment]
@okaufmann 

I could try that if I wanted to install the package and go to all the trouble of setting it up.

Or the author could simply answer the question and save us all a lot of time and trouble.

**Comment by okaufmann** [comment]
I think you found a way to fix your requirement meanwhile. Otherwise, feel free to open a new issue.
