### ISSUE TITLE
Class 'App\Team' not found

### ISSUE THREAD

**Issue by rxng** [mpociot/teamwork#136]
Follow the instructions and created the Team.php model file.

In Laravel 8, Models reside in their own folder, so this error occurs when 'team_model' => App\Team::class,

However, when I update it to App\Models\Team::class  , it also doesn't work.

Why is Laravel not detecting the Team model?

**Comment by okaufmann** [comment]
Do you have this problem only with teamwork related models?

**Comment by jhoanborges** [comment]
`composer dumpautoload`
