### ISSUE TITLE
Save() method not found

### ISSUE THREAD

**Issue by senthilvelpro** [mpociot/teamwork#14]
This is my controller

class TeamController extends Controller {

```
public function index()
{
    $app = new Application();
    $team = new Team($app);
    $team->owner_id = Auth::user()->id;
    $team->name = 'My awesome team';
    $team->save();
}
```

}

When i execute this nothing happens, because of the $items->save() method not found in class including parent "Mpociot\Teamwork\Teamwork" class.

Please can you help me how to save new team.

**Comment by mpociot** [comment]
What do you mean with `$items->save()`?

What does your `Team` model look like?

**Comment by senthilvelpro** [comment]
This is my Team model

<?php

namespace App\Http\Models;
use Illuminate\Foundation\Application;
use Mpociot\Teamwork\Teamwork;

class Team extends Teamwork {

}
?>

This is my Team controller

<?php

namespace App\Http\Controllers;
use App\Http\Models\Team;
use Illuminate\Support\Facades\Auth;
use Illuminate\Foundation\Application;
use Illuminate\Support\Facades\Redirect;

class TeamController extends Controller {

```
public function index()
{
    $app = new Application();
    $team = new Team($app);
    $team->owner_id = Auth::user()->id;
    $team->name = 'My awesome team';
    $team->save();
    return Redirect::to('dashboard')->with('message','New Team created successfully');
}
```

}
?>

This is my user model

<?php

namespace App\Http\Models;

use Illuminate\Database\Eloquent\Model;
use Mpociot\Teamwork\Traits\UserHasTeams;

class User extends Model {

```
use UserHasTeams;

protected  $table = 'users';
```

}
?>

I have routed to teamcontroller (Teamcontroller@index), whenever user tries to add new team. But the method "$item->save()" does not found. So it won't redirect nor display any errors.

**Comment by mpociot** [comment]
Your Team model is extending the wrong class.

It should be:

```
<?php namespace App;

use Mpociot\Teamwork\TeamworkTeam;

class Team extends TeamworkTeam
{
}
```

**Comment by senthilvelpro** [comment]
Solved. Model extending class is in documentation, maybe i didn't take a look at closely. 

Many thanks for your reply and this awesome package.

**Comment by mpociot** [comment]
You're welcome - let me know when you've built something with it :)
