### ISSUE TITLE
[FEATURE REQUEST] - Request To Join Team

### ISSUE THREAD

**Issue by shanerbaner82** [mpociot/teamwork#147]
Hard to believe I am the only one thinking this would be a beneficial event. Our current integration displays all teams one can join but we want some sort of admin approval when joining. So instead of sending an invitation to the potential team member to accept, we will send a request to the owner from the potential team member that the owner can approve or deny.

**Comment by okaufmann** [comment]
You are welcome to create a PR for adding this feature.
