### ISSUE TITLE
Invite new user by email

### ISSUE THREAD

**Issue by michellaurent** [mpociot/teamwork#15]
Is it possible to invite somebody that us not yet a user by email ? So, if it accept the invitation, it will have to register first and then will be automatically added to the team.

**Comment by sschlein** [comment]
Yes - that's exactly what teamwork does :-)

**Comment by mpociot** [comment]
You need to implement the auth logic on your own.
This package does not store any team related info in the session when joining teams.

So before joining the team you'll need to check if the user is authenticated , and if he isn't, store the team I'd in the session. 
After the registration check if the session contains a team I'd and join it.
