### ISSUE TITLE
Purpose of "type" in the invite table?

### ISSUE THREAD

**Issue by vicrau** [mpociot/teamwork#18]
Hi, 

what's the use of the "type" field in the invites table?
Is it to make a differentation between : 
- an admin that invites?
- a user that requests access?

Is this work in progress?

kind regards
Vic

**Comment by mpociot** [comment]
Hey,

that `type` field was meant to be an indicator wether the invitation was outgoing or if it was a triggered by a user requesting an invite.

I think I will remove it from version 2.0, because it's not used in this package.

**Comment by vicrau** [comment]
hmm, I would not remove it :-)
It's exactly the use case you have with invites.
Or it's triggered by the admin or team-owner... or people need to request access where the admin or team-owner decides to approve or decline.
