### ISSUE TITLE
Stripe integration

### ISSUE THREAD

**Issue by Jamesking56** [mpociot/teamwork#2]
When using this package in Laravel with Laravel cashier. What is the billable entity? Is it the owner of the team or the team itself (with the owner managing each associated team's billing settings)?

**Comment by sschlein** [comment]
It depends on your business model. We're using the owner of the team as billable entity. An owner could have multiple teams and pay for all of them. You could also bind the billable entity to a team model if you want to bind the subscription on a team basis. As flexible as possible :)

**Comment by Jamesking56** [comment]
I think I'll probably attach the Billable trait to the Team and have the owner as the only one with permission to manage billing for the team. This way its still secured but then if the owner is swapped with another user (the team maybe got bought out in real life), the billing info (if its a company card) would stay?

Opinions?

**Comment by mpociot** [comment]
Sounds like that's the best way to do it for your specific use case. :+1: 

And please let me know when you've built something awesome with the help of this module. I would love to list some "battle proofed" real world projects!

**Comment by tpharaoh** [comment]
@Jamesking56 I was just thinking the same question. Did you implement a subscription type thing using Cashier, or a custom implementation
