### ISSUE TITLE
Perhaps a setTeamOwner method?

### ISSUE THREAD

**Issue by kevinruscoe** [mpociot/teamwork#31]
Doesn't seem to have a handy method to set the owner of a team

**Comment by mpociot** [comment]
Would you be open to create a PR for this feature?

**Comment by ziming** [comment]
Does assigning a user id to owner_id in Team model also add an entry to team_user table?

**Comment by ziming** [comment]
Or is it expected that if you are a team owner of team X, there will not be an entry of you in user_team for team X?

**Comment by codedninja** [comment]
When you assign an user_id to owner_id of a Team you need to add to run `attachTeam()` afterwards.
