### ISSUE TITLE
Able to set alternative team id column name/key (team_id)

### ISSUE THREAD

**Issue by kyranb** [mpociot/teamwork#32]
I have an existing database structure that references a 'Tenant' (tenant_id') rather than team. Would you be open to including this as a dynamically set option (like the user model)?

Happy to submit a PR if so :)

Edit: Upon looking at the codebase, it would make it harder to read, so probably not worth it.

**Comment by mpociot** [comment]
Sure - if it's optional, I'd be happy to see a PR 👍
