### ISSUE TITLE
Accessing a Team Relation from User's currentTeam()

### ISSUE THREAD

**Issue by hellozach** [mpociot/teamwork#44]
I have this setup and working correctly (thanks!) but I'm having an issue using the Team model's relations.

Here is my Team.php model:

```
<?php

namespace App;

use Mpociot\Teamwork\TeamworkTeam;

class Team extends TeamworkTeam
{
    /**
     * Get all of the projects in a given team.
     */
    public function projects() {
        return $this->hasManyThrough('App\Project', 'App\Client');
    }

    /**
     * Get all of the clients for a given team.
     */
    public function clients() {
        return $this->hasMany('App\Client');
    }
}
```

I'm able to access clients() and projects() with the following:

```
$team = Team::findOrFail(auth()->user()->currentTeam->id);

$clients = $team->clients;
```

But not with this:

```
$clients = auth()->user()->currentTeam->clients;
```

Just trying to understand why the second method doesn't work (if it's something I'm doing wrong or if that is not how Laravel is setup).

**Comment by mpociot** [comment]
Could you provide a test case? This is working for me

**Comment by mpociot** [comment]
Please reopen if you have a valid test case
