### ISSUE TITLE
Command "make:teamwork" is not defined

### ISSUE THREAD

**Issue by RossIV** [mpociot/teamwork#45]
I'm trying to use this with an install of Laravel 5.1, but when I try to run `php artisan make:teamwork`, it errors out with `Command "make:teamwork" is not defined`. I followed all of the rest of the steps outlined, but this just will not work. I did run `composer dump-autoload`, but that didn't help. Any suggestions?

**Comment by RossIV** [comment]
Aha - I figured it out. The `make:teamwork` command doesn't exist in v2.0, only 3.0+. This wasn't obvious in the readme. I upgraded to Laravel 5.2, changed the version of the package to 3.0, and then it worked perfectly.

**Comment by mpociot** [comment]
Sorry for that. I'll update the README to avoid further confusion
