### ISSUE TITLE
Invite user who is not registered

### ISSUE THREAD

**Issue by chriship** [mpociot/teamwork#47]
From a cursory glance, I couldn't find anything in the code that deals with inviting someone who is not already registered to use the site. I just wanted to confirm whether that functionality is not in this package or I just missed it?

Thanks!

**Comment by mpociot** [comment]
You can invite other users who aren't registered to your application yet using this code:

``` php
Teamwork::inviteToTeam( $email, $team, function( $invite )
{
    // Send email to user / let them know that they got invited
});
```

Here's the documentation: https://github.com/mpociot/teamwork#inviting-others
