### ISSUE TITLE
[FR] UserInvitedToTeam - Event

### ISSUE THREAD

**Issue by TimoStahl** [mpociot/teamwork#51]
Hi all,

thanks for this great package.
I want to suggest a third event, if a user is invited to a team.

\Mpociot\Teamwork\Events\UserJoinedTeam
\Mpociot\Teamwork\Events\UserLeftTeam
**\Mpociot\Teamwork\Events\UserInvitedToTeam**

What do you think?

Regards,
Timo

**Comment by mpociot** [comment]
I like the idea. Are you willing to submit a PR?

**Comment by TimoStahl** [comment]
Yes I could send a PR today or in the next days.

**Comment by mpociot** [comment]
Great, thank you!

Timo notifications@github.com schrieb am Fr., 26. Aug. 2016, 2:51 nachm.:
