### ISSUE TITLE
working with Join

### ISSUE THREAD

**Issue by Alexmg86** [mpociot/teamwork#57]
Hi! How i can use teamwork, if i need Join in query?

Laravel ask me error:
"SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'team_id' in where clause is ambiguous (SQL: select `tasks`.*, `price_types`.`name` as `name_type` from `tasks` inner join `price_types` on `tasks`.`type_list` = `price_types`.`id` where `project_id` = 9 and `team_id` = 1 order by `id` asc)"

**Comment by Alexmg86** [comment]
i change trait UsedByTeams
static::addGlobalScope('team', function (Builder $builder) {
            static::teamGuard();
            $builder->where(**$builder->getQuery()->from . '.**team_id', auth()->user()->currentTeam->getKey());
        });

**Comment by mpociot** [comment]
Could you provide a pull request with that modification?
