### ISSUE TITLE
inTeam method for user

### ISSUE THREAD

**Issue by lukasoppermann** [mpociot/teamwork#60]
Hey @mpociot,
I think a method `inTeam($team)` or `isMemberOfTeam($team)` would be very useful for the `User` model.

For example when a user updates a something in a team and you want to check if the user is allowed to do this. It is basically used here: https://github.com/mpociot/teamwork/blob/master/src/Mpociot/Teamwork/Traits/UserHasTeams.php#L257

If you agree I would be willing to send a PR.

**Comment by mpociot** [comment]
Sure - feel free to send a PR! :)

**Comment by lukasoppermann** [comment]
I actually currently stoped developing in PHP and will not be using this (very awesome) package at the moment, so I won't send a PR.
