### ISSUE TITLE
Add Roles/Permissions to teams

### ISSUE THREAD

**Issue by codedninja** [mpociot/teamwork#61]
Add function so multiple users can manage a team. This way an "admin" of the team can manage the team but can't kick someone out.

**Comment by mpociot** [comment]
Don't know if this should be part of this package. You could just override the `isOwnerOfTeam` and method in your User model to add your extra checks.

**Comment by codedninja** [comment]
Decided to bash it out in last couple of days. I "think" it's ready would love some feed back on it.
https://github.com/tehcodedninja/TeamRoles
