### ISSUE TITLE
Share permissions between teams?

### ISSUE THREAD

**Issue by mcblum** [mpociot/teamwork#74]
Thank you for writing this awesome package! Does anyone have an idea of the best way to link two different teams so that they one team can access the permissions of another? Meaning, if team 1 has a bunch of products and team 2 is helping facilitate customer reviews for team 1, what would be the easiest way to allow team 2 to administer team 1's products without allowing team 1 access to all of team 2's stuff, since team 2 will be a service provider for the teams that are actually selling stuff?

Thanks again.

**Comment by mcblum** [comment]
Upon taking a closer look it appears as though maybe the easiest way is just to have the user switch teams temporarily.

**Comment by mpociot** [comment]
👍 I also think that this makes more sense for this package :)
