### ISSUE TITLE
User switching between teams and standalone user

### ISSUE THREAD

**Issue by R00118189** [mpociot/teamwork#75]
enhancement? This may be related to roles, I will ask anyway - I am looking for solution to switch between teams but also to (no team) stand alone user as not of all my users have teams. So when I switch to team my user shall have different roles assigned than when it is switched to standalone user.

**Comment by mpociot** [comment]
Hmm...I don't think this is really related to this package. This is bound to your project specific permission system in my opinion.

**Comment by R00118189** [comment]
You right, it may be not related, but nice feature to have.
