### ISSUE TITLE
Invite issue

### ISSUE THREAD

**Issue by spitfire64** [mpociot/teamwork#78]
Just to be clear, should laravel:auth be run before installing your repo? OR should it absolutely NOT be installed before? OR, maybe, it doesn't matter?

**Comment by spitfire64** [comment]
Can someone confirm these rules:
1 A register and login feature like laravel:auth is a good idea to start with.
2 A person  must have an active registration at the site in order to make an invitation to a team to work

**Comment by jenky** [comment]
2. I think so, it always take the current authenticated user to send the invitation.

**Comment by jenky** [comment]
And BTW, this package doesn't save the invited user to the team_invites table, it save the inviter instead. So when you're accepting an invite, it uses current authenticated user again, this could end up to incorrect user is being added to the team.

**Comment by okaufmann** [comment]
I'll close this since its an old issue. Feel free to open another if you still need help.
