### ISSUE TITLE
Possible issue in UserHasTeams Trait?

### ISSUE THREAD

**Issue by ghost** [mpociot/teamwork#8]
Hi there,

I'm toying around with your package and came across an issue, if one uses the package together with eg. the [Entrust](https://github.com/Zizaco/entrust) role based permission package.

If you add the EntrustUserTrait and the UserHasTeams Trait to your User Model, you'll cause an fatal error with the following message:

"Trait method boot has not been applied, because there are collisions with other trait methods on App\User"

Because both Traits have a boot method to reset the many to many relation on deletion. I'm not sure, if one can omit this by renaming the boot method to:

bootUserHasTeams

which should be called automatically by Laravel and don't call the parent boot method in that one. Also I'm not sure, if this keeps the desired behavior and works as expected?  
And yes I could have asked the same question in the Entrust repo, but I thought this one is better maintained :)

**Comment by mpociot** [comment]
Hi, 

thanks for reporting this issue!
I fixed it by using `bootUserHasTeams` as you suggested. :+1:

**Comment by ghost** [comment]
Hi,

great! Glad to help :+1: 
So, it still works as expected?
Came to another possible issue in the same method. I think in L5.\* the Trait for the SoftDelete feature is called [SoftDeletes](http://laravel.com/api/5.0/Illuminate/Database/Eloquent/SoftDeletes.html) and not [SoftDeletingTrait](http://laravel.com/api/4.2/Illuminate/Database/Eloquent/SoftDeletingTrait.html) like in L4.2, so the method body has to change to:

if ( !method_exists( \Config::get( 'auth.model' ), 'bootSoftDeletes' ) )

Or am I going in the wrong direction?

**Comment by mpociot** [comment]
Yes, you're right. Fixed it :)
