### ISSUE TITLE
memberofteam

### ISSUE THREAD

**Issue by marksie1988** [mpociot/teamwork#81]
Is there a way that we can check if a user is a member of any team?

i have a dropdown menu that users can switch teams from, the problem i have is that if the user is not a member of a team it just displays a laravel error. 

I created the following but it still errors or doesnt show the correct information: 
```
@if(is_null(Auth::user()->teams))
                            Select Site
                        @else
    			            @if(Auth::user()->currentTeam->name)
                                <i class="fa fa-users"></i> {{ Auth::user()->currentTeam->name }}
                            @else
                                Select Site
                            @endif
                        @endif
```

**Comment by jlndk** [comment]
If you have a teams relationship defined on your user model, you could do something like this

``` php
Auth::user()->teams->isNotEmpty()
```

**Comment by okaufmann** [comment]
I'll close this since its an old issue. Feel free to open another if you still need help.
