### ISSUE TITLE
Get teams that are not the currentTeam

### ISSUE THREAD

**Issue by RobertCordes** [mpociot/teamwork#85]
Is there a built-in way to get teams that are not the **`currentTeam`**? I've looked through the code and the issues but couldn't find anything. Right now I have my own solution:

```php
# User.php

public function otherTeams()
{
    if (is_null($this->currentTeam)) return $this->teams;

    $otherTeams = $this->teams->reject(function ($team) {
        return $team->getKey() == $this->currentTeam->getKey();
    });

    return $otherTeams;
}
```

This seems to work, but if there's already a way to do this I obviously would use that 😄

Best regards,
Robert

**Comment by okaufmann** [comment]
Unfortunately not. Maybe you'd like to create a PR?

**Comment by RobertCordes** [comment]
I don't even know which project I was working on at that time 🤔 But you’re right, it would’ve been a good idea to create a PR for that.
