### ISSUE TITLE
support for laravel 5.6

### ISSUE THREAD

**Issue by nsbucky** [mpociot/teamwork#88]
It seems like this will still work under laravel 5.6, can you update the dependency in the composer.json?

**Comment by Jrb1x** [comment]
Seconded.

**Comment by mkantautas** [comment]
Thirded.

**Comment by ExcellentSP** [comment]
Fourthded.

**Comment by rohanshukla94** [comment]
Fifthed

**Comment by mpociot** [comment]
I tagged a new release with 5.6 and 5.7 support
