### ISSUE TITLE
SQL Error Laravel 5.6

### ISSUE THREAD

**Issue by DarkBlue1231** [mpociot/teamwork#93]
Hello, 

i have a Problem. I will on localhost/team/ and than comes a Error by me.. 

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'teams.user_id' in 'where clause' (SQL: select * from `teams` where `teams`.`user_id` = 2 and `teams`.`user_id` is not null)

Can you help me Please

**Comment by okaufmann** [comment]
I'll close this since its an old issue. Feel free to open another if you still need help.

**Comment by mallria** [comment]
I got this error too.

**Comment by mallria** [comment]
I am working laravel 8.x
