### ISSUE TITLE
Can I use this package with Laravel 5.6?

### ISSUE THREAD

**Issue by karmendra** [mpociot/teamwork#95]
Can I use this package with Laravel 5.6? I do not see much activity on this project, can I consider this an active package?

**Comment by karmendra** [comment]
Looks not many care about this package anymore, is there any alternate?

**Comment by necenzurat** [comment]
laratrust but it's awful

**Comment by karmendra** [comment]
I am already using laratrust for roles and permissions but the team in that is really not easy to implement, lacks documentation as well. Anyways I am using this package for managing teams in my l5.6  project, seems to be working fine as of now.

**Comment by necenzurat** [comment]
i'm looking for a decent package with teams and roles built in.

**Comment by mpociot** [comment]
I tagged a new release with 5.6 and 5.7 support
