### ISSUE TITLE
TeamworkTeamTrait owner() method should be a BelongsTo relationship

### ISSUE THREAD

**Issue by spriggsey** [mpociot/teamwork#99]
Currently the relationship of the `Team` model is using the incorrect join.

The `owner()` relationship on the `Team` model should be a `belongsTo()` relationship as the `Team` model has the `owner_id` column.

The original code does work but with implementation of Laravel Nova it becomes an issue as they require a `BelongsTo` join to properly function.

https://github.com/mpociot/teamwork/blob/4de34f53c44757030ed54dde5f69fe48b7a207e1/src/Mpociot/Teamwork/Traits/TeamworkTeamTrait.php#L35-L46

**Comment by okaufmann** [comment]
This should be fixed now.
